-- =====================================================================
-- v2 schema. Run this in the Supabase SQL Editor before using the app.
--
-- v2 differs from v1 in three ways:
--   * the table is `entries_v2`, not `entries`
--   * a `previous_value` jsonb column holds the record's values from before
--     the most recent update
--   * `severity` and `impact` are constrained to High / Medium / Low
--
-- The app talks to Supabase exclusively from server-side route handlers using
-- the service_role key, so service_role is the only role that needs table
-- privileges -- anon stays locked out, meaning the browser never gets direct
-- database access.
-- =====================================================================

create table if not exists public.entries_v2 (
  id                bigint generated by default as identity primary key,
  agent_name        text not null,
  customer_name     text,
  summary           text,
  description       text,
  severity          text,
  impact            text,
  cost              numeric,
  customer_category text,
  previous_value    jsonb,
  created_at        timestamptz default now()
);

-- If the table already exists from an earlier run, add what v2 needs.
alter table public.entries_v2
  add column if not exists previous_value jsonb;

-- Constrained vocabularies. These mirror SEVERITY_LEVELS, IMPACT_LEVELS and
-- CUSTOMER_CATEGORIES in lib/fields.js -- change both together.
-- NULL stays allowed: only Agent Name is required.
alter table public.entries_v2
  drop constraint if exists entries_v2_severity_check;
alter table public.entries_v2
  add constraint entries_v2_severity_check
  check (severity in ('High', 'Medium', 'Low'));

alter table public.entries_v2
  drop constraint if exists entries_v2_impact_check;
alter table public.entries_v2
  add constraint entries_v2_impact_check
  check (impact in ('High', 'Medium', 'Low'));

alter table public.entries_v2
  drop constraint if exists entries_v2_customer_category_check;
alter table public.entries_v2
  add constraint entries_v2_customer_category_check
  check (customer_category in ('Basic', 'Silver', 'Gold', 'Platinum'));

-- Privileges. No delete: nothing in v2 removes a record -- agents add and
-- modify, auditors only read.
grant select, insert, update on table public.entries_v2 to service_role;

-- Grant on the id sequence too, if there is one. This covers both `serial` and
-- `generated as identity` columns, and is a no-op if id has neither.
do $$
declare seq text;
begin
  seq := pg_get_serial_sequence('public.entries_v2', 'id');
  if seq is not null then
    execute format('grant usage, select on sequence %s to service_role', seq);
  end if;
end $$;

-- Keep RLS on. service_role bypasses it; with no policies defined, the public
-- anon/authenticated roles remain unable to read or write the table.
alter table public.entries_v2 enable row level security;

-- Verify: should return (service_role, entries_v2, SELECT), (… INSERT), (… UPDATE).
-- select grantee, table_name, privilege_type
--   from information_schema.role_table_grants
--  where table_name = 'entries_v2' and grantee = 'service_role';

-- The list view sorts by created_at descending.
create index if not exists entries_v2_created_at_idx
  on public.entries_v2 (created_at desc);


-- =====================================================================
-- NOT RECOMMENDED: anon-key fallback.
-- Only if you cannot use a service_role key. The anon key ships to the
-- browser, so this makes the table world-readable and world-writable.
-- =====================================================================
-- grant select, insert, update on table public.entries_v2 to anon;
-- create policy "anon full access" on public.entries_v2
--   for all to anon using (true) with check (true);
